# Generated by Django 5.2.10 on 2026-03-02 06:20

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMostPurchase',
            fields=[
            ],
            options={
                'verbose_name': 'User w/ Most Purchases',
                'verbose_name_plural': 'Users w/ Most Purchases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
