# Generated by Django 5.0 on 2026-03-03 16:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMostComment',
            fields=[
            ],
            options={
                'verbose_name': 'User w/ Most Comments',
                'verbose_name_plural': 'Users w/ Most Comments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
