# Generated by Django 5.0 on 2026-03-08 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_city_order_country_order_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='longitufe',
            new_name='longitude',
        ),
    ]
